# Example Site settings

google_analytics: G-YQR3MX1GD4

header_pages:
  - index.md
  - 3eso.md
  - about.md

footer: 'sigueme en <a href="https://twitter.com/toomas_ps">twitter</a>'

style: # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
